language: python
python:
 - 2.7
 - 3.4
before_install:
 - sudo apt-get update -qq -y
 - sudo apt-get install -qq -y libgdal-dev gdal-bin python-gdal python-pip python-numpy build-essential git python-dev
env:
 - DJANGO_VERSION=1.6.5
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8.3
 - DJANGO_VERSION=1.8.5
 - DJANGO_VERSION=1.9.2
virtualenv:
 system_site_packages: false
install: 
 - wget https://pypi.python.org/packages/source/p/pysqlite/pysqlite-2.6.3.tar.gz
 - tar xzf pysqlite-2.6.3.tar.gz
 - cd pysqlite-2.6.3
 - sed -i '/SQLITE_OMIT_LOAD_EXTENSION/d' setup.cfg
 - sudo python setup.py install
 - cd ..
 - pip install unicodecsv
 - CFLAGS=-I/usr/include/gdal pip install GDAL
 - pip install coveralls
 - pip install Django==$DJANGO_VERSION
 - python setup.py -q install
script:
    coverage run --source etl_sync runtests.py
after_success:
    coveralls
