language: python
python:
 - "2.7"
before_install:
 - "sudo apt-get update -qq -y "
 - "sudo apt-get install -qq -y libgdal-dev gdal-bin python-gdal python-pip python-numpy build-essential git python-dev"
 - "wget https://pypi.python.org/packages/source/p/pysqlite/pysqlite-2.6.3.tar.gz"
 - "tar xzf pysqlite-2.6.3.tar.gz"
 - "cd pysqlite-2.6.3"
 - "sed -i '/SQLITE_OMIT_LOAD_EXTENSION/d' setup.cfg"
 - "sudo python setup.py install"
 - "cd .."
env:
# - DJANGO_VERSION=1.5.5
 - DJANGO_VERSION=1.6.5
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8
virtualenv:
 system_site_packages: true
install: 
 - pip install unicodecsv
 - CFLAGS=-I/usr/include/gdal pip install GDAL
 - pip install coveralls
 - pip install Django==$DJANGO_VERSION
script:
    coverage run --source etl_sync runtests.py
after_success:
    coveralls
