language: python
python:
 - "2.7"
before_install:
 - "sudo apt-get update -qq -y"
 - "sudo apt-get install -qq -y libgdal-dev gdal-bin build-essential git"
virtualenv:
 system_site_packages: true
install: 
 - "pip install ."   
 - "pip install -r requirements.txt"
 - "CFLAGS=-I/usr/include/gdal pip install GDAL==1.10.0"
    # command to run tests, e.g. python setup.py test
script:
    coverage run --source django-etl-sync python runtests.py
after_success:
    coveralls
