language: python
python:
  - "2.7"
before_install:
 - "sudo apt-get update -qq -y"
    # - "sudo apt-get install -qq -y libgdal-dev gdal-bin python-gdal python-pip python-numpy build-essential git python-dev"
    # virtualenv:
    # - system_site_packages: true
install: 
 - "pip install ."   
 - "pip install -r requirements.txt"
    # command to run tests, e.g. python setup.py test
script:
    - python etl_sync/runtests.py

