language: python

python:
 - '2.7'
 - '3.4'
 - '3.6'

env:
 - DJANGO_VERSION=1.7.0
 - DJANGO_VERSION=1.8.16
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.3
 - DJANGO_VERSION=1.11.6

before_install:
  - lsb_release -a
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -y install python-dev python3-dev libgdal-dev gdal-bin libstdc++6-4.6-dev
  - gdalinfo --version

install:
  - pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite || true
  - CFLAGS=-I/usr/include/gdal pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source etl_sync runtests.py && coverage report

after_success: coveralls
