language: python

python:
 - 2.7
 - 3.4
 - 3.6

env:
 - DJANGO_VERSION=1.7.0
 - DJANGO_VERSION=1.8.16
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.3
 - DJANGO_VERSION=1.11.6

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -y install libgdal-dev libstdc++6-4.6-dev

install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite
  - CFLAGS=-I/usr/include/gdal pip install GDAL==2.2
  - CFLAGS=-I/usr/include/gdal pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source etl_sync runtests.py && coverage report

after_success: coveralls
